### ISSUE TITLE
Remember me key

### ISSUE THREAD

**Issue by animator013** [nerdErg/grails-shiro#1]
Hi there!

I was thinking if we can add the possibility to change the cipher key for remember me tokens. It should add a little more security as can be read here https://shiro.apache.org/static/1.4.1/apidocs/org/apache/shiro/mgt/AbstractRememberMeManager.html. By default every project is using a default key which can be found in shiro's sources if not changed.

What do you think ? I can make a PR if necessary.

Btw great work on the rewritting of the plugin :)

**Comment by pmcneil** [comment]
Sounds like a great idea to me :-) PR welcome.

**Comment by pmcneil** [comment]
How would this work? perhaps

- script to generate a key
- config option to set it

**Comment by animator013** [comment]
I think a config option is the most convenient way.

**Comment by pmcneil** [comment]
yes, but also provide a script to generate a key to make it easy for people to make a secure key.

**Comment by pmcneil** [comment]
So MacProvider is part of https://github.com/jwtk/jjwt ... which I'll be adding to the plugin to implement the JWT realm Real Soon  Now

**Comment by animator013** [comment]
Pull request #3

**Comment by pmcneil** [comment]
Added
