### ISSUE TITLE
redirect uri does not add app name

### ISSUE THREAD

**Issue by carlosorrego** [nerdErg/grails-shiro#10]
asumes app starts at the root

so /auth/login does nosexiste as it laks the app name bejore

/appName/auth/login

how can i change this?

**Comment by pmcneil** [comment]
See the documentation here: https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc#redirecting-unauthenticated-and-unauthorized

Are you running in tomcat or from the runable war file?

**Comment by carlosorrego** [comment]
thanks, that did not work for me.
But i am running the war at path / now , so no problems. Thanks

**Comment by pmcneil** [comment]
I'd still like to know where you had trouble, so we can improve the documentation or possibly swat a bug :-)

**Comment by carlosorrego** [comment]
shir just did not recognize my app name in the path http://localhost:8080/appName

it would always asume the redirects to http://localhost:8080/
