### ISSUE TITLE
Can't make default project start with grails 3.2.11

### ISSUE THREAD

**Issue by amarchen** [nerdErg/grails-shiro#11]
Hi there 

I am trying to add shiro to my grails 3.2.11 project and tried studying default projects.
Environment:
- Mac OS X
- gradle 3.5.1 (both in system and gradlew)
- grails 3.2.11

Here's what I did:
```
grails create-app shiroweb --profile=web # also tried rest-api profile with the same results
added compile "org.grails.plugins:grails-shiro:3.1" to dependencies to build.gradle
./grailsw run-app # also tried gradle bootRun, ./gradlew bootRun
```

Whatever I do, code compiles fine and then stops in runtime with the following:
```
2019-11-08 18:36:03.896 ERROR --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception
...
2019-11-08 18:36:03.907 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplicationPostProcessor' defined in shiroweb.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is org.grails.core.exceptions.GrailsRuntimeException: Failed to introspect class: class shiro.Application
```

I tried studying the situation deeper and it actually throws in `DomainClassArtefactHandler.doIsDomainClassCheck()` when trying to `clazz.getAnnotation(Artefact.class);` for the shiro.Application class

Googling suggests that there is something wrong with the classpath - some needed class isn't in the classpath, maybe related to that grails-shiro uses gradle 5, unlike grails 3 (that is on gradle 3), but that's the end of my grails/gradle knowledge.k

**Comment by pmcneil** [comment]
First up: We re-wrote grails shiro on grails 3.3.10 and haven't really tested it on grails 3.2.x so there **may** be a problem there.
`Failed to introspect class: class shiro.Application` is interesting.
Could you perhaps try the above with grails 3.3.10 and see if you still have the problem?

**Comment by amarchen** [comment]
Tried with grails 3.3.11 - app starts and I am able to start login sequence and breakpoints work in IDEA's debugger. I still fail to actually login, but that's more about the details (default quickstart doesn't include demo users and naive attempt to use Bootstrap init from https://grails.org/plugins/shiro results in `java.lang.IllegalArgumentException: Invalid salt version`).

Now need to think on whether we could upgrade to 3.3 for shiro..
Funny thing is that we aren't even going to use more than just wildcard permission parsing. Another microservice is likely to pass a long set of permissions inside a JWT, I was going to pass this into a just-in-time created shiro user so that we could easily check permissions in controllers and services. Maybe I could somhow just reuse wildcard matcher for it.

**Comment by pmcneil** [comment]
OK good luck with that!
