### ISSUE TITLE
rememberMe on grails 3.3.9 not working

### ISSUE THREAD

**Issue by carlosorrego** [nerdErg/grails-shiro#14]
I can not make it work
i added to application,groovy 
security.shiro.authc.required = false

creates the cookie, but it does not remember me

**Comment by pmcneil** [comment]
We have tested on 3.3.10, and although I can't see why it wouldn't work on 3.3.9 it hasn't been tested. See test here https://github.com/nerdErg/grails-shiro/blob/e525a2361dae2977c93a563177812c06004db123/src/test/fixtures/tests/shiro-tester/integration-test/groovy/shiro/tester/AnnotatedServiceSpec.groovy#L88

To check some common issues if the class or method @RequiresAuthentication then you will have to log in even with remember me on.

**Comment by pmcneil** [comment]
Also check that your browser is not set to discard cookies on close, which I assume you have :-) Otherwise also checking you have seen https://nerderg.com/docs/shiro/guide.html#remember-me.

**Comment by carlosorrego** [comment]
I am using Shiro plug in version 3.1
Which one do you recommend? 
I love so far Shiro. Much simpler than spring.

**Comment by pmcneil** [comment]
grails-shiro plugin 3.2 is the latest version for Grails 3.x it uses Shiro version 1.4.2

**Comment by carlosorrego** [comment]
will it break something?

**Comment by pmcneil** [comment]
no

**Comment by carlosorrego** [comment]
trying 3.2 with no luck.
It just ignores the cookie.
Any idea on what to do or investigate?

thanks

**Comment by carlosorrego** [comment]
when i come back after closing browser  y see in AuthInterceptor.before()
that i get a valid SecurityUtils.subject.principal

so it is recognizing the cookie and creates the principal, but still it goes to signIn

**Comment by carlosorrego** [comment]
it seems to recognize the subject from the cookie, but it is not authenticated
how can i create an authToken just from the rememberMe cookie and the subject created?

**Comment by pmcneil** [comment]
Yes that is what remember me does. It gives you an un-authenticated subject, because they haven't logged in this session. So, if you're happy to accept remember me as enough of a credential (which I don't recommend for most things) then use @RequiresUser...

/**
Requires the current Subject to be an application <em>user</em> for the annotated class/instance/method to be accessed or invoked.  This is <em>less</em> restrictive than the {@link RequiresAuthentication RequiresAuthentication} annotation.
*/

**Comment by carlosorrego** [comment]
thanks mate. I truly read everything, this escape me.

Love the plugin, any help you need count on me.
cheers

**Comment by pmcneil** [comment]
No problem. I could not count the number of times I've read all the documentation, but obviously missed understanding it! I blame the documentation, so... if you have any suggestions on how the documentation can be improved I'd love to here them :-)
