### ISSUE TITLE
Problem using "grails install"

### ISSUE THREAD

**Issue by lvojnovic** [nerdErg/grails-shiro#15]
I am getting this error when running `grails install` in a plugin that has grails-shiro dependency

```
| Error Command [install] error: No such property: basedir for class: _Install
Possible solutions: baseDir (Use --stacktrace to see the full trace)
```

It seems it is due to the `src/main/scripts/_Install.groovy` in grails-shiro plugin.

The problem is easy to reproduce. Just run `grails install` in cloned grails-shiro.

Version of grails-shiro is 3.2
Version of grails is 3.3.11

I suggest removing the `_Install.groovy` considering it does not do it's original purpose in grails 3 (`/* Script invoked when the plugin is installed. */`). 
Perhaps it is also worth removing `_Uninstall.groovy` and `_Upgrade.groovy` for the same reason?

**Comment by animator013** [comment]
Well I think that 3 scripts are not necessary anyways. Maybe a fix would be to use camelCase `baseDir` in the script.

**Comment by pmcneil** [comment]
I have removed these, I haven't published these changes yet. If you need them just clone and build, see README.adoc
