### ISSUE TITLE
Unauthorized redirect missing context path

### ISSUE THREAD

**Issue by jonmor51** [nerdErg/grails-shiro#16]
In a Grails 4.0.2 app, with version 4.1 of the plugin, the unauthorized redirect, i.e., the URL the user is redirected to if not authorized, does not take account of the context path defined for the application (in server.servlet.context-path in application.groovy). So, for example, for my 'myapp' app, it comes up with http://localhost:8090/auth/login?targetUri=/myapp/mycontroller/myaction instead of http://localhost:8090/myapp/auth/login?targetUri=/myapp/mycontroller/myaction.  The problem is in the resolveViewOrRedirect method of ShiroGrailsExceptionResolver.groovy. This line does not take into account the context path: `String forwardUrl = UrlMappingUtils.buildDispatchUrlForMapping(info). 

Not sure whether a workaround for this is possible via settings? Bit of a showstopper as it is (as the redirect URL is not handled by my Grails app).

Small app attached which demonstrates the issue.
[myapp.zip](https://github.com/nerdErg/grails-shiro/files/4437762/myapp.zip)

`

**Comment by jonmor51** [comment]
I don't know whether this is part of the same issue, but setting 
`security:
    shiro:
        session:
            handleExceptions: false`
does not, in fact, result in the application using GrailsExceptionResolver instead of ShiroGrailsExceptionResolver as the docs seem to suggest - ShiroGrailsExceptionResolver still gets called,

**Comment by jonmor51** [comment]
The good news is that using accessControl() from an Interceptor doesn't exhibit this problem, so I have a workaround.

**Comment by pmcneil** [comment]
You can tell the ShiroGrailsExceptionResolver where to redirect via URL mapping for 403/401 see https://nerderg.com/docs/shiro/guide.html#redirecting-unauthenticated-and-unauthorized That should "just work".

Thanks for the feedback. We have tested the `handleExceptions: false` so I'd like to see if there has been a problem introduced.

**Comment by pmcneil** [comment]
I think `server.servlet.context-path` can be an issue. I have applications where we could only get `server.contextPath` to work... I'll give your app a try tomorrow.
Oh and the correct setting to turn off handle exceptions is `security.shiro.handleExceptions` (see https://github.com/nerdErg/grails-shiro/blob/e525a2361dae2977c93a563177812c06004db123/src/main/groovy/shiro/ShiroGrailsPlugin.groovy#L99)
Seems the documentation fell fowl of YAML indentation.

**Comment by jonmor51** [comment]
Thanks, I'll give that a go. There are a couple of problems with the documentation, incidentally, in this area. In AccessControl.loginRedirect(), there is this: `String redirectUri = grailsApplication.config.getProperty('security.shiro.login.uri')`. But in the docs, you have `url - default /auth/login (trumps controller/action)` - i.e., 'url' instead of 'uri'. Happy to help out with this kind of thing in whatever way I can, once I know what I'm doing!

**Comment by pmcneil** [comment]
pushed fixes to guide.adoc will get them online today

**Comment by jonmor51** [comment]
Is that a commit to fix the docs, or to address the issue with the context path?

**Comment by pmcneil** [comment]
docs

**Comment by pmcneil** [comment]
Sorry to take so long looking at context path issue again.

**Comment by pmcneil** [comment]
It looks like it's *possibly* a Grails 4 issue where the context-path isn't added to the DefaultUrlMapping Info - investigating.

**Comment by pmcneil** [comment]
latest commit upgrade to 4.3 of the plugin fixes the context-path issue and removes the use of the URL mapping as a separate configuration for Annotations. See the guide update for info.
I have re-written the ShiroGrailsExceptionResolver completely and separated it from the GrailsExceptionResolver. The result is a far more straight forward resolver that handles one job properly. It also uses the config for setting redirects for accessControl() Annotation based access.
Please give it a go and let me know of issues. I will modify the Grails 3 version now.

**Comment by jonmor51** [comment]
Thanks very much! I'll give it a go as soon as I get the chance.

**Comment by pmcneil** [comment]
Also updated the grails 3 version (grails 3 branch).

**Comment by jonmor51** [comment]
What am I missing?

`| Error Error initializing classpath: Could not find org.grails.plugins:grails-shiro:4.3.
Searched in the following locations:
  - https://repo.grails.org/grails/core/org/grails/plugins/grails-shiro/4.3/grails-shiro-4.3.pom
  - https://repo.grails.org/grails/core/org/grails/plugins/grails-shiro/4.3/grails-shiro-4.3.jar`

**Comment by pmcneil** [comment]
you need to install the plugin locally from source to test it out - I haven't published it yet :-)
I'm just implementing a few more tests before publishing (found a bug already!)

**Comment by pmcneil** [comment]
I have now published the plugins, both v3.3 and v4.3 they may take a while to show up on the grails plugin portal but you can see them at https://bintray.com/beta/#/nerderg/plugins/grails-shiro?tab=overview
this issue is now fixed :-)

**Comment by jonmor51** [comment]
I can confirm this is now working. Thanks!
